# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0c4151fe2dec586349339c9e7d91985ec421b572d52d378b73f624e86075570f6073925b427c953946b304c19189972cb03bf18a745e118ee9d1e6a4c0e82ecd

test:
  secret_key_base: 3cb7c054f723d31202dab64e6efd5f8a8cc388f37d919af548b8f94e7359b5d85303ae218dc2ddc1fd77e798c43b330e0cc31f4a60704cb3f82247810ca0e64a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: e156ab2e03aa99d58463e1eb1ffd0da86df1d05e2301a9654f69da922e1e4cba917bcd30d467f3dc3c7f228ebfb2d7170cd984cf98899cac743844e5eeede904
