require "application_system_test_case"

class QrVerificationsTest < ApplicationSystemTestCase
  setup do
    @qr_verification = qr_verifications(:one)
  end

  test "visiting the index" do
    visit qr_verifications_url
    assert_selector "h1", text: "Qr Verifications"
  end

  test "creating a Qr verification" do
    visit qr_verifications_url
    click_on "New Qr Verification"

    check "Checked in" if @qr_verification.checked_in
    fill_in "Checked in at", with: @qr_verification.checked_in_at
    fill_in "Checked in by", with: @qr_verification.checked_in_by_id
    fill_in "Code", with: @qr_verification.code
    fill_in "Expected time", with: @qr_verification.expected_time
    fill_in "Generated by", with: @qr_verification.generated_by_id
    fill_in "Notes", with: @qr_verification.notes
    fill_in "Purpose", with: @qr_verification.purpose
    fill_in "Site", with: @qr_verification.site_id
    fill_in "Valid till", with: @qr_verification.valid_till
    click_on "Create Qr verification"

    assert_text "Qr verification was successfully created"
    click_on "Back"
  end

  test "updating a Qr verification" do
    visit qr_verifications_url
    click_on "Edit", match: :first

    check "Checked in" if @qr_verification.checked_in
    fill_in "Checked in at", with: @qr_verification.checked_in_at
    fill_in "Checked in by", with: @qr_verification.checked_in_by_id
    fill_in "Code", with: @qr_verification.code
    fill_in "Expected time", with: @qr_verification.expected_time
    fill_in "Generated by", with: @qr_verification.generated_by_id
    fill_in "Notes", with: @qr_verification.notes
    fill_in "Purpose", with: @qr_verification.purpose
    fill_in "Site", with: @qr_verification.site_id
    fill_in "Valid till", with: @qr_verification.valid_till
    click_on "Update Qr verification"

    assert_text "Qr verification was successfully updated"
    click_on "Back"
  end

  test "destroying a Qr verification" do
    visit qr_verifications_url
    page.accept_confirm do
      click_on "Destroy", match: :first
    end

    assert_text "Qr verification was successfully destroyed"
  end
end
